/**
 * TaskGraphEmitter — T11
 *
 * Emits task_graph.yaml: the validated task graph in YAML format.
 * Contains all tasks, dependencies, file access declarations, priorities, and metadata.
 */

import { createHash } from 'node:crypto';
import { stringify } from 'yaml';
import type { Emitter, EmitterContext } from '../types.js';

/** Compute SHA-256 hash of string content. */
function contentHash(content: string): string {
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

/** Deterministic YAML stringify with sorted keys. */
function toYaml(data: unknown): string {
  return stringify(data, {
    sortMapEntries: true,
    lineWidth: 120,
    defaultStringType: 'PLAIN',
    defaultKeyType: 'PLAIN',
  });
}

export class TaskGraphEmitter implements Emitter {
  readonly name = 'task-graph';

  async emit(ctx: EmitterContext): Promise<void> {
    const input = ctx.taskGraphInput ?? {
      project: { name: ctx.projectName, description: 'Project generated by ATSF.', constraints: [] },
      tasks: [],
    };

    // Build the artifact object (without checksum first, for hashing)
    const artifact = {
      version: '1.0',
      generated: ctx.generatedAt,
      checksum: '', // placeholder
      project: input.project,
      tasks: input.tasks,
    };

    // Compute checksum of the data content (excluding checksum field itself)
    const dataForHash = { version: artifact.version, project: artifact.project, tasks: artifact.tasks };
    const yamlForHash = toYaml(dataForHash);
    artifact.checksum = contentHash(yamlForHash);

    const yamlOutput = toYaml(artifact);
    ctx.vfs.writeFile('task_graph.yaml', yamlOutput);
  }
}
