/**
 * i18n — Emitter language strings
 *
 * Provides translated section headings for emitted artifacts.
 * Default language is English ('en'). Currently supports 'en' and 'tr'.
 */

export interface EmitterStrings {
  // MPD headings
  masterPlanningDocument: string;
  tableOfContents: string;
  executiveSummary: string;
  projectOverview: string;
  objectives: string;
  targetAudience: string;
  scope: string;
  inScope: string;
  outOfScope: string;
  background: string;
  problemStatement: string;
  proposedSolution: string;
  successCriteria: string;
  technicalArchitecture: string;
  patterns: string;
  techStack: string;
  componentDesign: string;
  responsibilities: string;
  taskReferences: string;
  dataModel: string;
  apiDesign: string;
  securityConsiderations: string;
  testingStrategy: string;
  tools: string;
  coverageTarget: string;
  deploymentPlan: string;
  environments: string;
  riskAssessment: string;
  timeline: string;
  criticalPath: string;
  glossary: string;
  appendices: string;
  architecturalDecisionRecords: string;
  references: string;
  tests: string;

  // Ticket headings
  description: string;
  acceptanceCriteria: string;
  technicalNotes: string;
  relatedDecisions: string;
  given: string;
  when: string;
  then: string;

  // Prompt pack headings
  context: string;
  contract: string;
  outputFiles: string;
  dependencies: string;
  inputFilesReadOnly: string;
  previousTaskOutputs: string;
  instructions: string;
  doNot: string;
  testCriteria: string;
  complexity: string;
  suggestedModel: string;

  // Manifest
  generatedByAtsf: string;

  // Common
  project: string;
  generated: string;
  tasks: string;
}

const en: EmitterStrings = {
  masterPlanningDocument: 'Master Planning Document',
  tableOfContents: 'Table of Contents',
  executiveSummary: 'Executive Summary',
  projectOverview: 'Project Overview',
  objectives: 'Objectives',
  targetAudience: 'Target Audience',
  scope: 'Scope',
  inScope: 'In Scope',
  outOfScope: 'Out of Scope',
  background: 'Background',
  problemStatement: 'Problem Statement',
  proposedSolution: 'Proposed Solution',
  successCriteria: 'Success Criteria',
  technicalArchitecture: 'Technical Architecture',
  patterns: 'Patterns',
  techStack: 'Tech Stack',
  componentDesign: 'Component Design',
  responsibilities: 'Responsibilities',
  taskReferences: 'Task References',
  dataModel: 'Data Model',
  apiDesign: 'API Design',
  securityConsiderations: 'Security Considerations',
  testingStrategy: 'Testing Strategy',
  tools: 'Tools',
  coverageTarget: 'Coverage Target',
  deploymentPlan: 'Deployment Plan',
  environments: 'Environments',
  riskAssessment: 'Risk Assessment',
  timeline: 'Timeline',
  criticalPath: 'Critical Path',
  glossary: 'Glossary',
  appendices: 'Appendices',
  architecturalDecisionRecords: 'Architectural Decision Records',
  references: 'References',
  tests: 'Tests',

  description: 'Description',
  acceptanceCriteria: 'Acceptance Criteria',
  technicalNotes: 'Technical Notes',
  relatedDecisions: 'Related Decisions',
  given: 'Given',
  when: 'When',
  then: 'Then',

  context: 'Context',
  contract: 'Contract',
  outputFiles: 'Output Files',
  dependencies: 'Dependencies',
  inputFilesReadOnly: 'Input Files (Read-Only)',
  previousTaskOutputs: 'Previous Task Outputs',
  instructions: 'Instructions',
  doNot: 'DO NOT',
  testCriteria: 'Test Criteria',
  complexity: 'Complexity',
  suggestedModel: 'Suggested Model',

  generatedByAtsf: 'Generated by ATSF',

  project: 'Project',
  generated: 'Generated',
  tasks: 'Tasks',
};

const tr: EmitterStrings = {
  masterPlanningDocument: 'Ana Planlama Dokumani',
  tableOfContents: 'Icindekiler',
  executiveSummary: 'Yonetici Ozeti',
  projectOverview: 'Projeye Genel Bakis',
  objectives: 'Hedefler',
  targetAudience: 'Hedef Kitle',
  scope: 'Kapsam',
  inScope: 'Kapsam Dahilinde',
  outOfScope: 'Kapsam Disinda',
  background: 'Arka Plan',
  problemStatement: 'Problem Tanimi',
  proposedSolution: 'Onerilen Cozum',
  successCriteria: 'Basari Kriterleri',
  technicalArchitecture: 'Teknik Mimari',
  patterns: 'Kaliplar',
  techStack: 'Teknoloji Yigini',
  componentDesign: 'Bilesen Tasarimi',
  responsibilities: 'Sorumluluklar',
  taskReferences: 'Gorev Referanslari',
  dataModel: 'Veri Modeli',
  apiDesign: 'API Tasarimi',
  securityConsiderations: 'Guvenlik Degerlendirmesi',
  testingStrategy: 'Test Stratejisi',
  tools: 'Araclar',
  coverageTarget: 'Kapsama Hedefi',
  deploymentPlan: 'Dagitim Plani',
  environments: 'Ortamlar',
  riskAssessment: 'Risk Degerlendirmesi',
  timeline: 'Zaman Cizelgesi',
  criticalPath: 'Kritik Yol',
  glossary: 'Sozluk',
  appendices: 'Ekler',
  architecturalDecisionRecords: 'Mimari Karar Kayitlari',
  references: 'Referanslar',
  tests: 'Testler',

  description: 'Aciklama',
  acceptanceCriteria: 'Kabul Kriterleri',
  technicalNotes: 'Teknik Notlar',
  relatedDecisions: 'Ilgili Kararlar',
  given: 'Verilen',
  when: 'Oldugunda',
  then: 'Beklenen',

  context: 'Baglam',
  contract: 'Sozlesme',
  outputFiles: 'Cikti Dosyalari',
  dependencies: 'Bagimliliklar',
  inputFilesReadOnly: 'Girdi Dosyalari (Salt Okunur)',
  previousTaskOutputs: 'Onceki Gorev Ciktilari',
  instructions: 'Talimatlar',
  doNot: 'YAPMAYIN',
  testCriteria: 'Test Kriterleri',
  complexity: 'Karmasiklik',
  suggestedModel: 'Onerilen Model',

  generatedByAtsf: 'ATSF tarafindan uretildi',

  project: 'Proje',
  generated: 'Uretim Tarihi',
  tasks: 'Gorevler',
};

const STRINGS: Record<string, EmitterStrings> = { en, tr };

/**
 * Get translation strings for the given language code.
 * Falls back to English if the language is not supported.
 */
export function getStrings(lang: string): EmitterStrings {
  return STRINGS[lang] ?? STRINGS['en']!;
}

const LANG_NAMES: Record<string, string> = {
  en: 'English',
  tr: 'Turkish',
};

/**
 * Build a language directive to prepend to system prompts.
 * Instructs the LLM to generate all output in the configured language.
 * Returns empty string for 'en' (default behavior).
 */
export function langDirective(lang: string): string {
  if (lang === 'en') return '';
  const name = LANG_NAMES[lang] ?? lang;
  return `IMPORTANT: Generate ALL output content in ${name}, regardless of the input language.\n\n`;
}

/**
 * Prepend language directive to a system prompt if needed.
 */
export function withLangDirective(systemPrompt: string, lang: string): string {
  const directive = langDirective(lang);
  if (!directive) return systemPrompt;
  return directive + systemPrompt;
}
